export const students = [
  {
    name: 'Muhammad Shah',
    rollNo: 23523,
    degree: 'Bachelors',
    occupation: 'Software Engineer',
    Institute: 'Virtual University of Pakistan',
  },
  {
    name: 'Umair Amin',
    rollNo: 23524,
    degree: 'Associate',
    occupation: 'Computer Scientist',
    Institute: 'University of Lahore',
  },
  {
    name: 'Ayesha Khan',
    rollNo: 23525,
    degree: 'O-Level',
    occupation: 'IT Specialist',
    Institute: 'FAST NUCES',
  },
  {
    name: 'Ali Raza',
    rollNo: 23526,
    degree: 'A-Level',
    occupation: 'AI Researcher',
    Institute: 'NUST',
  },
  {
    name: 'Fatima Zahra',
    rollNo: 23527,
    degree: 'B.Ed',
    occupation: 'Data Scientist',
    Institute: 'Punjab University',
  },
  {
    name: 'Ahmed Hassan',
    rollNo: 23528,
    degree: 'Bachelors',
    occupation: 'Cyber Security Analyst',
    Institute: 'COMSATS Islamabad',
  },
  {
    name: 'Zainab Bukhari',
    rollNo: 23529,
    degree: 'Associate',
    occupation: 'Software Engineer',
    Institute: 'LUMS',
  },
  {
    name: 'Hassan Ali',
    rollNo: 23530,
    degree: 'O-Level',
    occupation: 'Game Developer',
    Institute: 'Superior University',
  },
  {
    name: 'Muqaddas Rafique',
    rollNo: 25430,
    degree: 'A-Level',
    occupation: 'HR Associate',
    Institute: 'FAST University',
  },
];
